name: snake_button
description: A button that appears with a snake animation along the border.
version: 0.0.1
homepage: https://github.com/CarmineToriello95/snake_button

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
